### ISSUE TITLE
Implement a CHANGELOG.MD

### ISSUE THREAD

**Issue by JamesHenry** [johannesjo/ng-fab-form#29]
Hi @johannesjo,

Thanks for all your hard work! It would be brilliant if you could provide a CHANGELOG so that it is easy for us to see when new features are added or bugs fixed.

It is currently really hard to know when/whether to update.

Many thanks,

James

**Comment by johannesjo** [comment]
Hello @JamesHenry,

thank you for message. I think a changelog is very good idea. However I'm not sure what would be the best (easiest) way to implement it. Do you have a suggestion how to implement one? I know there is https://github.com/btford/grunt-conventional-changelog but I don't want to rebase the whole repository.

In general you should be able to update without any problems. There was one big change in the implementation (implemented with v1.0.0), aftewards there were only bugfixes and smaller feature additions without changing the way how the existing ones are used.

**Comment by JamesHenry** [comment]
Thanks for the feedback @johannesjo. I am afraid I do not have any recommendations myself, but I appreciate you taking the time to think about this.

**Comment by johannesjo** [comment]
After thinking about the issue, I decided to not implement a changelog for now, as it probably won't be much better than this:
https://github.com/johannesjo/ng-fab-form/commits/master
Releases are labeled as such and the commit names should give you a good indicator, if you need to worry about upgrading. So far after the 0.er versions only one change has been introduced.

It's a little bit messy, because I experimented with some autodeploying grunt task and I'm hesitant to rebase everything as this might mess things up for some people.

Thank you again for your feedback. If it so happens that the repo will be a little bit more popular, there are more people working on it or that there are some bigger changes to come, I definitely will reconsider your suggestion. For now I suppose that - apart from testing - there is only one additional feature planned: async validators. But this probably won't change anything about how to use current features.
