### ISSUE TITLE
Support nested ng-forms

### ISSUE THREAD

**Issue by psavage** [johannesjo/ng-fab-form#69]
If a `<form>` element contains a nested `<ng-form>` like this:

```html
<form>
    <ng-form>
        <input type="text" required ng-model="testInput">
    </ng-form>
</form>
```

The validation messages template is not injected into the inputs within the `<ng-form>` and a `TypeError: Cannot read property 'emailRegex' of undefined` error occurs because `ngFabFormConfig` is not defined on the child form's controller:

```javascript
if (!cfg) {
    cfg = formCtrl.ngFabFormConfig;
}

// overwrite email-validation
if (cfg.emailRegex && attrs.type === 'email') {  // Error occurs here because "cfg" is undefined"
    ngModelCtrl.$validators.email = function (value)
    {
        return ngModelCtrl.$isEmpty(value) || cfg.emailRegex.test(value);
    };
}
```

**Comment by johannesjo** [comment]
That's probably because ng-fab-form for now only applies to the form element, but not to ng-form. I'll try to look into it as soon as I can. Meanwhile pull-requests are of course welcome. Not sure what's the most elegant solution to apply a directive to differently named elements, but for the input elements ng-fab-form uses a directive-factory.

**Comment by psavage** [comment]
Ok thanks. Perhaps you could do something similar to how [Angular registers the form and ng-form directives](https://github.com/angular/angular.js/blob/cc961888cd4d37b112864db69486bc83daea7010/src/ng/directive/form.js#L451).

**Comment by johannesjo** [comment]
Thanks for the suggestion. I added the support for ng-form. Could you check it out?

**Comment by psavage** [comment]
Works great! Thanks for the quick fix. Keep up the great work!
